### ISSUE TITLE
Login/signup

### ISSUE THREAD

**Issue by ameenkhan07** [ameenkhan07/ebill#4]
Convert the landing page to its php counterpart.
ie ensure login.php and signup.php are maintained with their rescpective forms along with #3

**Comment by developerfranso** [comment]
hello im trying to host it in xampp and DB is not working

**Comment by bndanyi** [comment]
What help do you need?

**Comment by developerfranso** [comment]
whenever i try to import database it responds like this......
![dff](https://cloud.githubusercontent.com/assets/8489071/8228157/5d24cfe8-15b5-11e5-89d7-e219ba2b392c.PNG)

**Comment by developerfranso** [comment]
hey i have solved the issue i re edited the sql file let me see how i can make ur system better

**Comment by ameenkhan07** [comment]
@developerfranso , try running queries via the query option in Phpmyadmin.
I used cursor functions for some tasks, which usually cause these problems.
HINT: Build the database then run the cursor functions.

**Comment by developerfranso** [comment]
ok
